<?php
return [   
        'admins' => 'Manage Admins',
        'products' => 'Manage Products',
        'categories' => 'Manage Categories',
        'brands' => 'Manage Brands',
        'coupons' => 'Manage Coupons',
        'orders' => 'Manage Orders',
        'users' => 'Manage Users',
        'roles' => 'Manage Roles',
        'settings' => 'Manage Settings',
        'reports' => 'Manage Reports',
        'dashboard' => 'Manage Dashboard',
        'profile' => 'Manage Profile',
        'home' => 'Manage Home',
        'contact' => 'Manage Contact',
        'about' => 'Manage About',
        'blog' => 'Manage Blog',
        'newsLetters' => 'Manage News Letters',
        'banners' => 'Manage Banners',
        'sliders' => 'Manage Sliders',
        'pages' => 'Manage Pages',
        'faqs' => 'Manage FAQs',
        'comments' => 'Manage Comments',
        'socials' => 'Manage Socials',
        'menus' => 'Manage Menus',  
        'global_shipping' => 'Manage Shipping', 
];
